"""add_clicks_table

Revision ID: 999918d0c02e
Revises: 1add3a791db3
Create Date: 2026-08-20 22:42:53.974359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '999918d0c02e'
down_revision: Union[str, None] = '1add3a791db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clicks_timestamp'), 'clicks', ['timestamp'], unique=False)
    op.create_index(op.f('ix_clicks_url_id'), 'clicks', ['url_id'], unique=False)
    op.create_index('ix_clicks_url_id_timestamp', 'clicks', ['url_id', 'timestamp'], unique=False)
    op.alter_column('urls', 'id',
               existing_type=sa.INTEGER(),
               comment='Internal ID',
               existing_comment='Internal ID — never exposed to API clients',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('urls', 'short_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Public short code',
               existing_comment="Public short code (e.g., 'abc1234')",
               existing_nullable=False)
    op.alter_column('urls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation timestamp',
               existing_comment='When this URL was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('urls', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Expiration timestamp (NULL = never)',
               existing_comment='When this URL expires (NULL = never)',
               existing_nullable=True)
    op.alter_column('urls', 'last_clicked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last click timestamp',
               existing_comment='When this URL was last clicked',
               existing_nullable=True)
    op.alter_column('urls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp',
               existing_comment='Last modification timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'urls',
        existing_comment='Core table storing all shortened URLs',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'urls',
        'Core table storing all shortened URLs',
        existing_comment=None,
        schema=None
    )
    op.alter_column('urls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last modification timestamp',
               existing_comment='Last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('urls', 'last_clicked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this URL was last clicked',
               existing_comment='Last click timestamp',
               existing_nullable=True)
    op.alter_column('urls', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this URL expires (NULL = never)',
               existing_comment='Expiration timestamp (NULL = never)',
               existing_nullable=True)
    op.alter_column('urls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this URL was created',
               existing_comment='Creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('urls', 'short_code',
               existing_type=sa.VARCHAR(length=20),
               comment="Public short code (e.g., 'abc1234')",
               existing_comment='Public short code',
               existing_nullable=False)
    op.alter_column('urls', 'id',
               existing_type=sa.INTEGER(),
               comment='Internal ID — never exposed to API clients',
               existing_comment='Internal ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_clicks_url_id_timestamp', table_name='clicks')
    op.drop_index(op.f('ix_clicks_url_id'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_timestamp'), table_name='clicks')
    op.drop_table('clicks')
    # ### end Alembic commands ###
