# ======================================================
# repositories/url_repository.py — Data Access Layer
# ======================================================
# SYSTEM DESIGN CONCEPT: Repository Pattern
# -------------------------------------------------
# The Repository pattern creates a BOUNDARY between your
# business logic and your database. It acts like a
# "collection" of domain objects that happens to be
# backed by a database.
#
# WHY IS THIS SO IMPORTANT?
#
# Without Repository Pattern:
#   Route Handler → SQLAlchemy queries → Database
#   (business logic and DB queries are MIXED together)
#
# With Repository Pattern:
#   Route Handler → Service → Repository → Database
#   (each layer has ONE job)
#
# BENEFITS:
# 1. TESTABILITY — Mock the repository in tests, no DB needed
# 2. SWAPPABILITY — Change from PostgreSQL to MongoDB?
#    Only the repository changes. Routes stay the same.
# 3. SINGLE RESPONSIBILITY — Repository ONLY does data access.
#    No business logic (validation, rate limiting, etc.)
# 4. REUSABILITY — Multiple services can use the same repository
#
# REAL-WORLD ANALOGY:
# Think of a library (the building, not the code kind):
# - YOU (route handler) want a book
# - LIBRARIAN (repository) knows WHERE books are stored
# - You don't care if books are on shelf A3 or in the basement
# - If the library switches to digital, the librarian's job
#   changes, but YOUR interface stays the same: "give me book X"
# ======================================================

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import select, delete, func, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import URL


class URLRepository:
    """
    Data access layer for URL operations.

    Every method here corresponds to a DATABASE OPERATION.
    No business logic — just CRUD (Create, Read, Update, Delete).

    DESIGN DECISION: Class vs Functions
    -----------------------------------
    We use a class (not standalone functions) because:
    1. Groups related operations together
    2. Can hold shared state (session) via __init__
    3. Easy to mock in tests (mock one class, not 10 functions)
    4. Can be extended with caching in Phase 3
    """

    def __init__(self, session: AsyncSession):
        """
        Initialize with a database session.

        DEPENDENCY INJECTION at the repository level:
        The repository doesn't CREATE its own session —
        it RECEIVES one. This means the caller controls
        the session lifecycle (commit, rollback, close).
        """
        self.session = session

    # --------------------------------------------------
    # CREATE
    # --------------------------------------------------

    async def create(self, url: URL) -> URL:
        """
        Insert a new URL into the database.

        SYSTEM DESIGN CONCEPT: Write Path
        ---------------------------------
        The write path is:
        1. session.add() — Stage the object (like git add)
        2. session.commit() — Write to DB (like git commit)
        3. session.refresh() — Reload with DB-generated values
           (id, created_at, server defaults)

        WHY refresh? Because some values are generated by the
        DATABASE, not Python (auto-increment ID, timestamps).
        After commit, we refresh to get those values back.
        """
        self.session.add(url)
        await self.session.commit()
        await self.session.refresh(url)
        return url

    # --------------------------------------------------
    # READ
    # --------------------------------------------------

    async def get_by_short_code(self, short_code: str) -> Optional[URL]:
        """
        Find a URL by its short code.

        This is the MOST CALLED method in the entire system
        because every redirect goes through it. That's why
        short_code has a database INDEX.

        GENERATED SQL:
            SELECT * FROM urls WHERE short_code = :code LIMIT 1

        WITHOUT index: Full table scan → O(n) → SLOW
        WITH index:    B-tree lookup  → O(log n) → FAST

        For 1 million URLs:
        - Without index: ~1,000,000 row comparisons
        - With index:    ~20 row comparisons (log2(1M) ≈ 20)
        """
        stmt = select(URL).where(URL.short_code == short_code)
        result = await self.session.execute(stmt)
        return result.scalar_one_or_none()

    async def get_all(
        self,
        skip: int = 0,
        limit: int = 10,
    ) -> list[URL]:
        """
        Get all URLs with pagination.

        SYSTEM DESIGN CONCEPT: Offset Pagination
        ----------------------------------------
        SQL: SELECT * FROM urls ORDER BY created_at DESC
             LIMIT :limit OFFSET :skip

        OFFSET pagination is simple but has a FLAW:
        For skip=1000000, the DB must scan 1 million rows
        just to skip them. This gets slower as offset grows.

        In Phase 3+, we'll discuss CURSOR-BASED pagination
        which doesn't have this problem:
        SELECT * FROM urls WHERE created_at < :last_seen
        ORDER BY created_at DESC LIMIT :limit

        For our URL shortener, offset pagination is fine
        because the list endpoint is rarely used at scale.
        """
        stmt = (
            select(URL)
            .order_by(URL.created_at.desc())  # Newest first
            .offset(skip)
            .limit(limit)
        )
        result = await self.session.execute(stmt)
        return list(result.scalars().all())

    async def count(self) -> int:
        """
        Count total URLs.

        Useful for pagination metadata:
        { "total": 1500, "page": 3, "per_page": 10 }
        """
        stmt = select(func.count(URL.id))
        result = await self.session.execute(stmt)
        return result.scalar_one()

    # --------------------------------------------------
    # UPDATE
    # --------------------------------------------------

    async def increment_click(self, short_code: str) -> Optional[URL]:
        """
        Atomically increment click count and update last_clicked_at.

        SYSTEM DESIGN CONCEPT: Atomic Updates
        -------------------------------------
        We use SQL UPDATE with click_count = click_count + 1
        instead of:
        1. Read current count → count = url.click_count
        2. Increment in Python → count += 1
        3. Write back → url.click_count = count

        WHY? Because step 1-3 has a RACE CONDITION:
        If two requests read count=5 simultaneously, both
        write count=6. We LOST a click!

        SQL `click_count = click_count + 1` is ATOMIC —
        the database handles the read-modify-write in a
        single operation. No race condition.

        This is one of the most common bugs in web apps,
        and one of the most common system design interview
        questions: "How do you handle concurrent updates?"
        """
        stmt = (
            update(URL)
            .where(URL.short_code == short_code)
            .values(
                click_count=URL.click_count + 1,  # Atomic increment
                last_clicked_at=datetime.now(timezone.utc),
            )
            .returning(URL)  # Return the updated row
        )
        result = await self.session.execute(stmt)
        await self.session.commit()
        return result.scalar_one_or_none()

    # --------------------------------------------------
    # DELETE
    # --------------------------------------------------

    async def delete_by_short_code(self, short_code: str) -> bool:
        """
        Delete a URL by short code.

        Returns True if a row was deleted, False if not found.

        SYSTEM DESIGN CONCEPT: Hard Delete vs Soft Delete
        ------------------------------------------------
        HARD DELETE: Actually removes the row (what we do here)
        SOFT DELETE: Sets a `deleted_at` timestamp, row stays

        Soft delete advantages:
        - Can recover accidentally deleted URLs
        - Audit trail (who deleted what, when)
        - Analytics on deleted URLs still work
        - Foreign key references don't break

        Soft delete disadvantages:
        - Every query needs WHERE deleted_at IS NULL
        - Database grows forever (never shrinks)
        - GDPR compliance harder (data must be truly deleted)

        We use hard delete for simplicity. In production,
        you'd typically soft delete with a cleanup job that
        hard-deletes after 30 days.
        """
        stmt = delete(URL).where(URL.short_code == short_code)
        result = await self.session.execute(stmt)
        await self.session.commit()
        return result.rowcount > 0

    async def short_code_exists(self, short_code: str) -> bool:
        """
        Check if a short code is already taken.

        PERFORMANCE NOTE: This does a SELECT EXISTS(...)
        which is faster than fetching the full row when
        you only need to know IF it exists.
        """
        stmt = select(URL.id).where(URL.short_code == short_code)
        result = await self.session.execute(stmt)
        return result.scalar_one_or_none() is not None
